from .candidat import Candidat
from .chomage import Chomage 
from .departement import Departement
from .election_stats import ElectionStats
from .election import Election
from .fait_securite import FaitSecurite
from .immigration import Immigration    
from .indicateur import Indicateur
from .population_departement import PopulationDepartement
from .resultats_election import ResultatElection
from .sexe import Sexe
from .tranche_age import TrancheAge
from .unite_de_compte import UniteDeCompte